In [6]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('database.csv')

C:\Users\HP\AppData\Local\Temp\ipykernel_1660\3714807356.py:1: DtypeWarning: Columns (9,12,15,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('database.csv')


In [11]:
df.head()

Record ID  Incident Year  Incident Month  Incident Day Operator ID  \
0     127128           1990               1             1         DAL   
1     129779           1990               1             1         HAL   
2     129780           1990               1             2         UNK   
3       2258           1990               1             3         MIL   
4       2257           1990               1             3         MIL   

          Operator   Aircraft Aircraft Type Aircraft Make Aircraft Model  ...  \
0  DELTA AIR LINES  B-757-200             A           148             26  ...   
1     HAWAIIAN AIR       DC-9             A           583             90  ...   
2          UNKNOWN    UNKNOWN           NaN           NaN            NaN  ...   
3         MILITARY      A-10A             A           345            NaN  ...   
4         MILITARY       F-16             A           561            NaN  ...   

   Fuselage Strike  Fuselage Damage Landing Gear Strike  Landing Gear Damage  \
0                0                0                   0                    0   
1                0                0                   0                    0   
2                0                0                   0                    0   
3                0                0                   0                    0   
4                0                0                   0                    0   

  Tail Strike Tail Damage  Lights Strike Lights Damage  Other Strike  \
0           1           1              0             0             0   
1           0           0              0             0             1   
2           0           0              0             0             0   
3           0           0              0             0             0   
4           0           0              0             0             0   

  Other Damage  
0            0  
1            0  
2            0  
3            0  
4            0  

[5 rows x 66 columns]

In [49]:
df_x=df.iloc[:10,:10]
df_y=df.iloc[:10,10:11]

In [116]:
df_x['Record ID']=['Brazil','iran','pakistan','iran','Brazil','Brazil','iran','pakistan','iran','pakistan']
df_y['Aircraft Mass']=['Yes','No','No','Yes','Yes','Yes','Yes','No','Yes','No']
#df_x = df_x.drop('Incident Day',axis =1)

In [117]:
df_x

Record ID  Incident Year Aircraft Make Aircraft Model
0    Brazil           1990           148             26
1      iran           1990           583             90
2  pakistan           1990           NaN            NaN
3      iran           1990           345            NaN
4    Brazil           1990           561            NaN
5    Brazil           1990           583             90
6      iran           1990           NaN            NaN
7  pakistan           1990           NaN            NaN
8      iran           1990           NaN            NaN
9  pakistan           1990           303             10

In [118]:
X = df_x.values
Y = df_y.values

In [119]:
# taking care of missing data

In [144]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,2:4])
X[:,2:4] = imputer.transform(X[:,2:4])

In [145]:
X

array([[1.0, 0.0, 0.0, 1990.0, 148.0, 26.0],
       [0.0, 1.0, 0.0, 1990.0, 583.0, 90.0],
       [0.0, 0.0, 1.0, 1990.0, 420.5, 54.0],
       [0.0, 1.0, 0.0, 1990.0, 345.0, 54.0],
       [1.0, 0.0, 0.0, 1990.0, 561.0, 54.0],
       [1.0, 0.0, 0.0, 1990.0, 583.0, 90.0],
       [0.0, 1.0, 0.0, 1990.0, 420.5, 54.0],
       [0.0, 0.0, 1.0, 1990.0, 420.5, 54.0],
       [0.0, 1.0, 0.0, 1990.0, 420.5, 54.0],
       [0.0, 0.0, 1.0, 1990.0, 303.0, 10.0]], dtype=object)

In [146]:
# Encoding Categorial Data

In [147]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0] )],remainder='passthrough')
X = ct.fit_transform(X)

In [148]:
# Independent Variable
X

array([[0.0, 1.0, 0.0, 0.0, 1990.0, 148.0, 26.0],
       [1.0, 0.0, 1.0, 0.0, 1990.0, 583.0, 90.0],
       [1.0, 0.0, 0.0, 1.0, 1990.0, 420.5, 54.0],
       [1.0, 0.0, 1.0, 0.0, 1990.0, 345.0, 54.0],
       [0.0, 1.0, 0.0, 0.0, 1990.0, 561.0, 54.0],
       [0.0, 1.0, 0.0, 0.0, 1990.0, 583.0, 90.0],
       [1.0, 0.0, 1.0, 0.0, 1990.0, 420.5, 54.0],
       [1.0, 0.0, 0.0, 1.0, 1990.0, 420.5, 54.0],
       [1.0, 0.0, 1.0, 0.0, 1990.0, 420.5, 54.0],
       [1.0, 0.0, 0.0, 1.0, 1990.0, 303.0, 10.0]], dtype=object)

In [149]:
# Dependent Varaiable


In [150]:
from sklearn .preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [151]:
Y

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [152]:
# Splitting Dataset

In [153]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [154]:
Y_train

array([1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [155]:
# Feature Scaling

In [156]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [157]:
X_train[:,3:]=sc.fit_transform(X_train[:,3:])

In [158]:
X_train

array([[1.0, 0.0, 1.0, -0.3779644730092272, 0.0, -0.1069833044692538,
        -0.27788057376105213],
       [0.0, 1.0, 0.0, -0.3779644730092272, 0.0, 0.9164144336025868,
        -0.27788057376105213],
       [0.0, 1.0, 0.0, -0.3779644730092272, 0.0, -2.091865038452005,
        -1.6925453129082266],
       [1.0, 0.0, 1.0, -0.3779644730092272, 0.0, -0.6569230142516308,
        -0.27788057376105213],
       [1.0, 0.0, 1.0, -0.3779644730092272, 0.0, 1.0766617662544054,
        1.5409740908567435],
       [1.0, 0.0, 0.0, 2.6457513110645903, 0.0, -0.1069833044692538,
        -0.27788057376105213],
       [1.0, 0.0, 1.0, -0.3779644730092272, 0.0, -0.1069833044692538,
        -0.27788057376105213],
       [0.0, 1.0, 0.0, -0.3779644730092272, 0.0, 1.0766617662544054,
        1.5409740908567435]], dtype=object)

In [161]:
X_test[:,3:]=sc.transform(X_test[:,3:])

In [162]:
X_test

array([[1.0, 0.0, 0.0, 2.6457513110645903, 0.0, -0.1069833044692538,
        -0.27788057376105213],
       [1.0, 0.0, 0.0, 2.6457513110645903, 0.0, -0.9628497402232842,
        -2.500925163849469]], dtype=object)